//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Tvdb.xsd {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Episode {
        
        private string idField;
        
        private string combined_episodenumberField;
        
        private string combined_seasonField;
        
        private string dVD_chapterField;
        
        private string dVD_discidField;
        
        private string dVD_episodenumberField;
        
        private string dVD_seasonField;
        
        private string directorField;
        
        private string epImgFlagField;
        
        private string episodeNameField;
        
        private string episodeNumberField;
        
        private string firstAiredField;
        
        private string guestStarsField;
        
        private string iMDB_IDField;
        
        private string languageField;
        
        private string overviewField;
        
        private string productionCodeField;
        
        private string ratingField;
        
        private string ratingCountField;
        
        private string seasonNumberField;
        
        private string writerField;
        
        private string absolute_numberField;
        
        private string airsafter_seasonField;
        
        private string airsbefore_episodeField;
        
        private string airsbefore_seasonField;
        
        private string filenameField;
        
        private string lastupdatedField;
        
        private string seasonidField;
        
        private string seriesidField;
        
        private string thumb_addedField;
        
        private string thumb_heightField;
        
        private string thumb_widthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Combined_episodenumber {
            get {
                return this.combined_episodenumberField;
            }
            set {
                this.combined_episodenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Combined_season {
            get {
                return this.combined_seasonField;
            }
            set {
                this.combined_seasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DVD_chapter {
            get {
                return this.dVD_chapterField;
            }
            set {
                this.dVD_chapterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DVD_discid {
            get {
                return this.dVD_discidField;
            }
            set {
                this.dVD_discidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DVD_episodenumber {
            get {
                return this.dVD_episodenumberField;
            }
            set {
                this.dVD_episodenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DVD_season {
            get {
                return this.dVD_seasonField;
            }
            set {
                this.dVD_seasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Director {
            get {
                return this.directorField;
            }
            set {
                this.directorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EpImgFlag {
            get {
                return this.epImgFlagField;
            }
            set {
                this.epImgFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EpisodeName {
            get {
                return this.episodeNameField;
            }
            set {
                this.episodeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EpisodeNumber {
            get {
                return this.episodeNumberField;
            }
            set {
                this.episodeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FirstAired {
            get {
                return this.firstAiredField;
            }
            set {
                this.firstAiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GuestStars {
            get {
                return this.guestStarsField;
            }
            set {
                this.guestStarsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IMDB_ID {
            get {
                return this.iMDB_IDField;
            }
            set {
                this.iMDB_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Overview {
            get {
                return this.overviewField;
            }
            set {
                this.overviewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductionCode {
            get {
                return this.productionCodeField;
            }
            set {
                this.productionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RatingCount {
            get {
                return this.ratingCountField;
            }
            set {
                this.ratingCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SeasonNumber {
            get {
                return this.seasonNumberField;
            }
            set {
                this.seasonNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Writer {
            get {
                return this.writerField;
            }
            set {
                this.writerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string absolute_number {
            get {
                return this.absolute_numberField;
            }
            set {
                this.absolute_numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string airsafter_season {
            get {
                return this.airsafter_seasonField;
            }
            set {
                this.airsafter_seasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string airsbefore_episode {
            get {
                return this.airsbefore_episodeField;
            }
            set {
                this.airsbefore_episodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string airsbefore_season {
            get {
                return this.airsbefore_seasonField;
            }
            set {
                this.airsbefore_seasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastupdated {
            get {
                return this.lastupdatedField;
            }
            set {
                this.lastupdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seasonid {
            get {
                return this.seasonidField;
            }
            set {
                this.seasonidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seriesid {
            get {
                return this.seriesidField;
            }
            set {
                this.seriesidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string thumb_added {
            get {
                return this.thumb_addedField;
            }
            set {
                this.thumb_addedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string thumb_height {
            get {
                return this.thumb_heightField;
            }
            set {
                this.thumb_heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string thumb_width {
            get {
                return this.thumb_widthField;
            }
            set {
                this.thumb_widthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet {
        
        private Episode[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Episode")]
        public Episode[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
